### ISSUE TITLE
Cc and Bcc recipients are not getting the message sent when using SMTP method

### ISSUE THREAD

**Issue by sarahleecb** [fmbiete/Z-Push-contrib#103]
Compose mail with 'field to' ok.
but, field cc can't send in ios.

postfix log show only to recipient sent but cc recipient nothing 

please advice
sorry for my bad english.

**Comment by corradofiore** [comment]
I am experiencing the same problem here, using the Sendmail method.  As a workaround, I switched to SMTP and it's working fine.

**Comment by fmbiete** [comment]
Hi @corradofiore,

Yes, mail and sendmail methods had the same problem. I have moved the fix into the BackendIMAP so all three shared the same solution.
