### ISSUE TITLE
sqlstatemachine.php does not handle null byte state data with Postgresql

### ISSUE THREAD

**Issue by jpfox156** [fmbiete/Z-Push-contrib#109]
My configuration is as follows: latest z-push contrib configured with an sql state machine using a Postgresql backend. State data is stored in a field of type text, in line with the MySQL.sql table setup. 

The serialized state_data often contains NULL byte characters. This is particularly the case for the hierarchy cache . Unfortunately either PDO or Postgresql doesn't do so well with null byte characters and truncates the state data. I'm not sure whether this is unique to Postgres or affects MySQL as well.

My solution (although admittedly a hack) is to slash-encode/decode non-printable characters before/after loading into the cache. My changes are as follows:

[line 181]        $data = unserialize(stripcslashes($record["state_data"]);
[line 223]        $params[":data"] = addcslashes(serialize($state), "\00..\31!@\177..\377);

Other options appear to be:
- base64 encode the entire state_data. given the 4/3 expansion of the data, this seemed undesirable. 
- use Bytea (Blob) data type within the database. I tried this and although it makes loading data into the cache straight forward (no need to encode unprintable characters), getting the data back out is a bit more of a challenge as PDO returns as resource pointer instead of a string. 
- use the file statemachine instead. This is probably the easiest option but I was set on persisting with the sql statemachine.

Obviously the above is a bit hack-ish, I'm sure their are smarter ways but I'm quite limited in my knowledge of php.

Regards,

James

**Comment by fmbiete** [comment]
I will close this as fixed.

If someone out there has problems using postgresql, please tell me.
