### ISSUE TITLE
IMAP Prefix with Cyrus

### ISSUE THREAD

**Issue by zero-one-devteam** [fmbiete/Z-Push-contrib#125]
Hi,

I am trying to use z-push-contrib with fastmail. They are using Cyrus and in there FAQs they advise to set the IMAP prefix to INBOX. So I did within the imap/config.php, but without success. Some of my folder do have the prefix Inbox, e.g. Inbox.ToDo etc.

Did I miss anything?

**Comment by fmbiete** [comment]
Can you provide any log/info??

**Comment by zero-one-devteam** [comment]
There seems to be "Double Inbox". The Folders IR and Domains eg are subfolders of INBOX, but the logs show them as INBOX.Inbox.Domains. 

When accessing the server via IMAP on iOS and entering INBOX as prefix the structure is correct. 



04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX') = eadedf6d
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX.Inbox.IR') = 8d167122
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX.Inbox.IR') = 8d167122
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX') = eadedf6d
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX') = eadedf6d
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX.Inbox.Domains') = 3006b487
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX.Inbox.Domains') = 3006b487
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX') = eadedf6d
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX') = eadedf6d
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX.Inbox.4-AnyTime') = 5040a7c3
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX.Inbox.4-AnyTime') = 5040a7c3
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX') = eadedf6d
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX') = eadedf6d
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX.Inbox.3-Warten') = cf7db9f7
04/01/2015 09:30:02 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX.Inbox.3-Warten') = cf7db9f7
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX') = eadedf6d
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX') = eadedf6d
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX.Inbox.2-Lesen') = 8e96a6df
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX.Inbox.2-Lesen') = 8e96a6df
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX') = eadedf6d
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX') = eadedf6d
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX.Inbox.1-ToDo') = 9f59d5ad
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX.Inbox.1-ToDo') = 9f59d5ad
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX') = eadedf6d
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX') = eadedf6d
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX.Drafts') = 0fbb8cf6
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX.Drafts') = 0fbb8cf6
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX') = eadedf6d
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX') = eadedf6d
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->getFolderIdFromImapId('INBOX') = eadedf6d
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->convertImapId('INBOX') = eadedf6d
04/01/2015 09:30:03 [14491] [DEBUG] [user@domain.com] BackendIMAP->Logoff(): IMAP connection closed

**Comment by zero-one-devteam** [comment]
Confusing. Tried to access the imap server via commandline and it shows me exactly:

* LIST (\HasNoChildren) "." INBOX.Inbox.1-ToDo
* LIST (\HasNoChildren) "." INBOX.Inbox.2-Lesen
* LIST (\HasNoChildren) "." INBOX.Inbox.3-Warten
* LIST (\HasNoChildren) "." INBOX.Inbox.4-AnyTime
* LIST (\HasNoChildren) "." INBOX.Inbox.Domains
* LIST (\HasNoChildren) "." INBOX.Inbox.IR

Seems that I have to filter the second "Inbox" out in the imap.php. Could you please give me a hint, where I should do it?
