### ISSUE TITLE
calDAV sync with cyrus

### ISSUE THREAD

**Issue by zero-one-devteam** [fmbiete/Z-Push-contrib#126]
Trying to sync with cyrus calDAV: Creating an appointment via calDAV (e.g. with Apple Calendar App or via Webfrontend) works well and the event will be synced to iOS. Editing this event on iOS does not work. e.g. moving it to another day will revert the changes after a few seconds.

Logfile shows this:

02/01/2015 07:55:32 [19108] [DEBUG] [user@domain.com] BackendCalDAV->Logon(): User 'user@domain.com' is authenticated on CalDAV
02/01/2015 07:55:32 [19108] [DEBUG] [user@domain.com] BackendCalDAV->StatMessage('C9c176090-8a3f-4ab2-b8e0-2586cdd8f299','a8a6ee05-b4aa-4a7e-a2b6-f89d4f93b489.ics')
02/01/2015 07:55:32 [19108] [DEBUG] [user@domain.com] BackendCalDAV->GetMessageList('C9c176090-8a3f-4ab2-b8e0-2586cdd8f299','1417503332')
02/01/2015 07:55:32 [19108] [DEBUG] [user@domain.com] BackendCalDAV->StatMessage('C9c176090-8a3f-4ab2-b8e0-2586cdd8f299','a8a6ee05-b4aa-4a7e-a2b6-f89d4f93b489.ics')
02/01/2015 07:55:32 [19108] [DEBUG] [user@domain.com] BackendCalDAV->StatMessage('C9c176090-8a3f-4ab2-b8e0-2586cdd8f299','a8a6ee05-b4aa-4a7e-a2b6-f89d4f93b489.ics')
02/01/2015 07:55:32 [19108] [DEBUG] [user@domain.com] BackendCalDAV->GetMessage('C9c176090-8a3f-4ab2-b8e0-2586cdd8f299','a8a6ee05-b4aa-4a7e-a2b6-f89d4f93b489.ics')
02/01/2015 07:55:32 [19108] [DEBUG] [user@domain.com] BackendCalDAV->_ParseVEventToAS(): Parsing VEvent
02/01/2015 07:55:32 [19108] [DEBUG] [user@domain.com] BackendCalDAV->Logoff()
02/01/2015 07:55:33 [19113] [DEBUG] [user@domain.com] BackendCalDAV->Logoff()
02/01/2015 07:55:34 [15929] [DEBUG] [user@domain.com] BackendCalDAV->Logon(): User 'user@domain.com' is authenticated on CalDAV
02/01/2015 07:55:34 [15929] [DEBUG] [user@domain.com] BackendCalDAV->ChangesSinkInitialize(): folderid 'C9c176090-8a3f-4ab2-b8e0-2586cdd8f299'02/01/2015 07:55:35 [24046] [DEBUG] [user@domain.com] BackendCombined->ChangesSink - Calling in 'BackendCalDAV' with 2
02/01/2015 07:55:36 [15929] [DEBUG] [user@domain.com] BackendCalDAV->GetMessageList('C9c176090-8a3f-4ab2-b8e0-2586cdd8f299','1417503336')
02/01/2015 07:55:37 [15929] [DEBUG] [user@domain.com] BackendCalDAV->StatMessage('C9c176090-8a3f-4ab2-b8e0-2586cdd8f299','a8a6ee05-b4aa-4a7e-a2b6-f89d4f93b489.ics')
02/01/2015 07:55:41 [24046] [DEBUG] [user@domain.com] BackendCalDAV->Logoff()

**Comment by fmbiete** [comment]
Put your loglevel to WEBXML.
After editing an event in iOS you must see a call to BackendCalDAV->ChangeMessage.That function is the responsible to store your changes in the caldav server.

**Comment by zero-one-devteam** [comment]
Thanks for this hint. Looks like Z-Push recognizes a conflict:

04/01/2015 10:26:37 [26120] [DEBUG] [user@domain.com] BackendCalDAV->StatMessage('C9c176090-8a3f-4ab2-b8e0-2586cdd8f299','a8a6ee05-b4aa-4a7e-a2b6-f89d4f93b489.ics')
04/01/2015 10:26:37 [26120] [ INFO] [user@domain.com] StatusException: ImportChangesDiff->ImportMessageChange('a8a6ee05-b4aa-4a7e-a2b6-f89d4f93b489.ics','SyncAppointment'): Conflict detected. Data from PIM will be dropped! Server overwrites PIM. User is informed. - code: 7

In fact there isn't any conflict, but I try to modify an event on iOS.

**Comment by zero-one-devteam** [comment]
A workaround seems to be this setting:

define('SYNC_CONFLICT_DEFAULT', SYNC_CONFLICT_OVERWRITE_SERVER);

Don't know if it makes sense to set it to PIM wins.

**Comment by zero-one-devteam** [comment]
Confusing. Tried to access the imap server via commandline and it shows me exactly:

* LIST (\HasNoChildren) "." INBOX.Inbox.1-ToDo
* LIST (\HasNoChildren) "." INBOX.Inbox.2-Lesen
* LIST (\HasNoChildren) "." INBOX.Inbox.3-Warten
* LIST (\HasNoChildren) "." INBOX.Inbox.4-AnyTime
* LIST (\HasNoChildren) "." INBOX.Inbox.Domains
* LIST (\HasNoChildren) "." INBOX.Inbox.IR

Seems that I have to filter the second "Inbox" out in the imap.php. Could you please give me a hint, where I should do it?

**Comment by fmbiete** [comment]
Use that option witch care!! You will lose changes if the user works with various emails clients (desktop and mobile for example).
