### ISSUE TITLE
IOS: calDAV appointment dashed when no organizer is set

### ISSUE THREAD

**Issue by zero-one-devteam** [fmbiete/Z-Push-contrib#127]
Hi, when adding an appointment via caldav on device A (eg MacBook) that is synced to device B (iOS) it appears dashed on device b (like an invitation which has not been answered yet). A workaround is to put the following line into backend/caldav/caldav.php:

After:
$properties = $event->GetProperties(); 
 foreach ($properties as $property) 
I inserted:
$message->organizeremail = sprintf("%s", $this->_username);

Is there any better solution?

**Comment by fmbiete** [comment]
Hi @zero-one-devteam 

Can you look if there's some line like this (DEBUG level):
```
BackendCalDAV->_ParseVEventToSyncObject(): '%s' is not yet supported.
```
I will use your workaround for now, see referenced commit, but there should be an organizer in the dav event.

**Comment by zero-one-devteam** [comment]
I double cheched the logs, but no line like 
BackendCalDAV->_ParseVEventToSyncObject(): '%s' is not yet supported.

**Comment by fmbiete** [comment]
Could you post the raw dav event text?

**Comment by fmbiete** [comment]
I will close this as fixed in the referenced commit.
