### ISSUE TITLE
Invitations on iOS, no RSVP button

### ISSUE THREAD

**Issue by zero-one-devteam** [fmbiete/Z-Push-contrib#131]
Hi,

when opening an e-mail with an invitation on iOS I do not see the rsvp buttons (accept, decline etc.).

I send invites from different servers to myself (outlook.de, yahoo, fastmail ...). I receive the email with the ics attachment. But when clicking on the attachment, I only have the option "add to calendar" and the organizuer won't be informed if I will attend.

Is this a known limitation?

Thanks,

Andreas

**Comment by fmbiete** [comment]
Yes, that functionality is a work in progress.

**Comment by fmbiete** [comment]
#108

**Comment by polytan02** [comment]
Would it be difficult to implement this function ? I have to say that it is the last function I miss so as to be able to use active sync on my phone instead of imap+carddav+caldav.

**Comment by fmbiete** [comment]
Hi @zero-one-devteam , @polytan02

Drenalina (www.drenalina.com) has kindly sponsored the implementation of those missing features. So it's testing time for "meetings".

**Comment by polytan02** [comment]
I can manage to have a test server to participate.

I have only BB10 phones.

**Comment by fmbiete** [comment]
@polytan02 That would be wonderful. I don't have BB10.

You can put the last code in your server and test it. Let me know if you find any problems.

Thanks!!
