### ISSUE TITLE
no invitation is sent when meeting is created

### ISSUE THREAD

**Issue by polytan02** [fmbiete/Z-Push-contrib#136]
Hello,

Please find output of testing-caldav.php there : 
https://mcgva.ovh/zerobin/?f6adfcf4421e88e6#SQR4tyCgZ7r0hOoLxJjBhMzu2d88/J4e59UryUD8Pg4=

The system is composed of debain 7 + Baikal + devocot + postfix + Z-push.

I don't know why, but when I create a calendar event from my phone inviting people, email is sent but without text notr attachment.

If I send the same using the native caldav implemetation of my phone, it works (Blackberry Passport runing 10.3.0.X)

Any idea where I should look at please ?

**Comment by fmbiete** [comment]
Hi @polytan02 ,

Yes, that funcionality (in BackendIMAP) is not yet complete: #108, #131

**Comment by fmbiete** [comment]
Hi @polytan02

Drenalina (www.drenalina.com) has kindly sponsored the implementation of those missing features. So it's testing time for "meetings".

**Comment by polytan02** [comment]
No problem, I can manage to have a treating server and participate to tests.
Just let me know ;)
