### ISSUE TITLE
Class 'XMLElement' not found

### ISSUE THREAD

**Issue by MisterM74** [fmbiete/Z-Push-contrib#137]
Good Morning
My include directory, XML files are the:
<pre>drwxr-xr-x  3 www-data www-data  4096 Feb  1 05:10 Auth
-rwxr-xr-x  1 www-data www-data 36094 Feb  1 05:10 caldav-client-v2.php
-rwxr-xr-x  1 www-data www-data 60802 Feb  1 05:10 iCalendar.php
drwxr-xr-x  2 www-data www-data  4096 Feb  1 05:10 Mail
-rwxr-xr-x  1 www-data www-data 10637 Feb  1 05:10 Mail.php
-rwxr-xr-x  1 www-data www-data 42260 Feb  1 05:10 mimeDecode.php
-rwxr-xr-x  1 www-data www-data 45234 Feb  1 05:10 mimePart.php
drwxr-xr-x  2 www-data www-data  4096 Feb  1 05:10 Net
-rwxr-xr-x  1 www-data www-data  5033 Feb  1 05:10 stringstreamwrapper.php
-rw-r--r--  1 www-data www-data 11075 Feb  1 13:11 XMLDocument.php
-rw-r--r--  1 www-data www-data 11276 Feb  1 13:11 XMLElement.php
-rwxr-xr-x  1 www-data www-data 30471 Feb  1 05:10 z_caldav.php
-rwxr-xr-x  1 www-data www-data 30951 Feb  1 05:10 z_carddav.php
-rwxr-xr-x  1 www-data www-data 32570 Feb  1 05:10 z_RFC822.php
-rwxr-xr-x  1 www-data www-data 32585 Feb  1 05:10 z_RTF.php</pre>

But I still have the error message:

<pre>PHP message: PHP Fatal error:  Class 'XMLElement' not found in /usr/share/z-push/include/z_caldav.php on line 387</pre>

I am stuck for idea

Michel

**Comment by chises** [comment]
Hi,
did you add the /usr/share/awl/inc path to you php.ini?

https://github.com/fmbiete/Z-Push-contrib/issues/71#issuecomment-48845234

**Comment by fmbiete** [comment]
Yep, as @chises said you need the php-awl-libs in your php path; for backends caldav and carddav.
