### ISSUE TITLE
Outlook 2013 CalDAV error

### ISSUE THREAD

**Issue by chises** [fmbiete/Z-Push-contrib#141]
Hi,
i am using a caldav backend.
If i am going to create a new entry i get the following warning:
24/02/2015 15:43:10 [  904] [ WARN] [test@domain.net] /var/www/z-push/include/z_caldav.php:348 Undefined property: CalDAVClient::$httpRequest (8)

Outlook is waiting for the Server-Response and get no answers.
I cant find the parameter httpRequest in file z_caldav.php.

My nginx Settings:
server {
        listen 443 ssl spdy;
        rewrite ^/Microsoft-Server-ActiveSync /z-push/index.php$1 redirect;
        rewrite ^/Autodiscover/Autodiscover.xml /z-push/autodiscover/autodiscover.php$1 redirect;
        rewrite ^/autodiscover/autodiscover.xml /z-push/autodiscover/autodiscover.php$1 redirect;
        location ~ \.php(?:$|/) {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_param HTTPS on;
                fastcgi_param PHP_VALUE "register_globals=0\nerror_reporting=E_ALL";
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_read_timeout 630;
        }
}

**Comment by chises** [comment]
update
z-push-top printout
10736 <outlook client ip>   <user>        Sync            01:03   Outlook/15.0 (15.0.4569.1.. f019a3e1f609404c87ab28851394eb8d Creating new message from mobile 1

**Comment by fmbiete** [comment]
Hi @chises ,

The referenced commit should remove that undefined error. Let me know if it works.

**Comment by chises** [comment]
create/edit a caldav event with outlook is not working. 
But hits strange issue is solved.
i will open a new issue with some logs.

B
