### ISSUE TITLE
 BackendIMAP->GetFolderList(): imap_list failed

### ISSUE THREAD

**Issue by chises** [fmbiete/Z-Push-contrib#155]
I have this warning:

13/03/2015 21:02:42 [18225] [WARN] [user@mail.de] BackendIMAP->GetFolderList(): imap_list failed:
13/03/2015 21:02:42 [18225] [WARN] [user@mailcoca.de] StatusException: ExportChangesDiff->InitializeExporter(): error, no folders available from the backend - code: 12 - file: /var/www/Z-Push-contrib/lib/default/diffbackend/exportchangesdiff.php:105

On line 666 @ ./backend/imap/imap.php i added this line
ZLog::Write(LOGLEVEL_WARN, sprintf("FOLDERS: <%s>", print_r($list)));
->
13/03/2015 21:02:42 [18225] [WARN] [user@mail.de] FOLDERS: <1>

Any ideas?

NOTE:
$mbox = imap_open("{mail.de:993/imap/ssl/novalidate-cert}", "user@mail.de", "user", OP_HALFOPEN)
      or die("can't connect: " . imap_last_error());

$list = imap_list($mbox, "{mail.de}", "*");

Result: {mailcoca.de}INBOX

**Comment by fmbiete** [comment]
Try executing imap_getsubscribed instead of imap_list.

I think your user it's not subscribed to any folder. What is your IMAP server?

**Comment by chises** [comment]
I tried this Setup with a new e-mail Account. 
Mailserver is @ debian a postfix/dovecot Setup.
I will come back after more testing :)

Note:if i use a simple php Script with imap_list i get INBOX
For testing i added a imap folder. 
Additional folderpath: INBOX.test

In z-push imap config i set default folder to INBOX.

**Comment by fmbiete** [comment]
This should be fixed with commit referenced in #157 

Reopen the issue if it doesn't work for you.

Thanks!

**Comment by chises** [comment]
@fmbiete thank you, fixed! :)
