### ISSUE TITLE
Function Problem

### ISSUE THREAD

**Issue by norm2k** [fmbiete/Z-Push-contrib#162]
There is a problem with backend/imap/imap.php
Line 745 should read:
 `if (strcasecmp($imapid, $this->create_name_folder(IMAP_FOLDER_INBOX)) == 0) {`
Line 750
`else if (strcasecmp($imapid, $this->create_name_folder(IMAP_FOLDER_DRAFT)) == 0) {`
Line 755
`else if (strcasecmp($imapid, $this->create_name_folder(IMAP_FOLDER_SENT)) == 0) {`
Line 761
`else if (strcasecmp($imapid, $this->create_name_folder(IMAP_FOLDER_TRASH)) == 0) {`

Once the function is referenced as above, it works.
Fails on:
PHP 5.4.38-0+deb7u1

Thanks for all the hard work.

**Comment by fmbiete** [comment]
Indeed, I missed to put "$this->" for the new calls.

Thanks!
