### ISSUE TITLE
Address validation failed when sending mail to some recipients - character encoding 

### ISSUE THREAD

**Issue by pasjojo** [fmbiete/Z-Push-contrib#164]
Hi, 
I am pleased to use z-push-contrib on a Ubuntu Server with gmail addresses. 
It work very well except when i try to send email to some recipients from my IOS devices.

Some of my recipients looks like :

Joël P. <<joel@a.domain.fr>>
 
The error in the z-push-contrib log : z_RFC822 error: Validation failed for: =?utf-8?Q?"Jo=C3=ABl_P."?= <joel@a.domain.fr>

<pre>
25/03/2015 16:25:33 [ 1719] [INFO] [joel@xxx.fr] Version='SVN-trunk-r1935' method='POST' from='80.14.0.18' cmd='SendMail' getUser='joel@xxx.fr' devId='u15d25q7bt63pabnrtgoqls6js' devType='iPhone'
25/03/2015 16:25:33 [ 1719] [INFO] [joel@xxx.fr] FileStateMachine->GetUserDevicePermission(): Pre-authorized device 'u15d25q7bt63pabnrtgoqls6js' for user 'joel@xxx.fr'
25/03/2015 16:25:33 [ 1719] [ERROR] [joel@xxx.fr] z_RFC822 error: Validation failed for: =?utf-8?Q?"Jo=C3=ABl_P."?= <joel@a.domain.fr>
25/03/2015 16:25:33 [ 1719] [WARN] [joel@xxx.fr] /var/www/Z-Push-contrib-master/include/Net/SMTP.php:364 Use of undefined constant PEAR_ERROR_RETURN - assumed 'PEAR_ERROR_RETURN' (8)
25/03/2015 16:25:33 [ 1719] [ERROR] [joel@xxx.fr] Net_SMTP error: Invalid response code received from server
</pre>

My server locales setting is "fr_FR.UTF-8" locales, but i had also tried "en_US.UTF-8"

I'am using the 'smtp' method in the Imap Backend and a local exim4 server, but the issue is the same with the php mail method. 

Thank you for your help.

**Comment by t3chguy** [comment]
This happens on my ubuntu system too

**Comment by pasjojo** [comment]
It's ok with : Joël P <joel@a.domain.fr>   so the problem seems to come from the '.'  at the end of "Joël P." in my first example. (and not the umlaut).

**Comment by fmbiete** [comment]
Hi @pasjojo,

The 2 referenced commits should fix the problem. Test again and let me know if it works.

Thanks!

**Comment by pasjojo** [comment]
Hi,

I just tested with the last commit : it works fine !

Thanks !
