### ISSUE TITLE
Autodiscover not working

### ISSUE THREAD

**Issue by sealand210** [fmbiete/Z-Push-contrib#165]
1. if browse via web goes straight into z-push info page without authentication
2. if try create a account on iPhone, it will indicate unable to verify account information
3. no error logs in apache and no error logs in z-push

certificate and domain record all ok, tested with a pre-configured autodiscover.xml

**Comment by fmbiete** [comment]
Hi @sealand210 ,

At the moment I don't use the autodiscover functionality, so I cannot help you so much with it.
Just to tick tasks, does z-push work with manual configuration?

**Comment by t3chguy** [comment]
if iOS uses autodiscover then it is working fine on my iPad. I am routing any request containing (case insensitive) /autodiscover to the autodiscover.php and all other requests to the index.php for z-push-contrib

**Comment by chises** [comment]
@sealand210 
can you verfiy autodiscovery with this:
https://testconnectivity.microsoft.com/

for me it is working.
nginx version: nginx/1.6.2
PHP 5.4.39-0+deb7u1

**Comment by t3chguy** [comment]
if it helps,
Nginx Ver: 1.6.2
PHP ver: PHP 5.6.7-1+deb.sury.org~trusty+1

**Comment by sealand210** [comment]
Thanks for your reply!

Z-push is working with IMAP backend, push mail is working fine. But I couldn't get it to work with CalDav or CardDav (from openxchange), the log reads it has passed the authentication but the phone is not getting any data.

Test result from Microsoft Connectivity Test (failed at the last step):

 	The Microsoft Connectivity Analyzer failed to obtain an Autodiscover XML response.
 	
	Additional Details
 	
An HTTP 401 Unauthorized response was received from the remote Unknown server. This is usually the result of an incorrect username or password. If you are attempting to log onto an Office 365 service, ensure you are using your full User Principal Name (UPN).
HTTP Response Headers:
Vary: Accept-Encoding
Content-Length: 0
Content-Type: text/html
Date: Thu, 02 Apr 2015 14:50:28 GMT
Server: Apache
WWW-Authenticate: Basic realm="ZPush"
Elapsed Time: 13879 ms.

My setup is Apache/2.2.22+ PHP 5.4.39-0+deb7u1

**Comment by fmbiete** [comment]
Happy that you found the solution :laughing: 

The server address with the full fqdn in the config is a nasty bit... I cannot use the same code with multiples fqdn.
