### ISSUE TITLE
SMTP Too Strict SSL Checking in PHP5.6

### ISSUE THREAD

**Issue by t3chguy** [fmbiete/Z-Push-contrib#168]
```
02/04/2015 17:26:02 [19653] [DEBUG] [postmaster@webdevguru.co.uk] Net_SMTP DEBUG: Recv: 220 2.0.0 Ready to start TLS
02/04/2015 17:26:02 [19653] [ WARN] [postmaster@webdevguru.co.uk] /var/www/z-push-contrib/include/Net/Socket.php:697 stream_socket_enable_crypto(): Peer certificate CN=`phoenix.webdevguru.co.uk' did not match expected CN=`localhost' (2)
02/04/2015 17:26:02 [19653] [DEBUG] [postmaster@webdevguru.co.uk] Net_SMTP DEBUG: Send: QUIT
```
localhost and 127.0.0.1 are considered secure, and the SSL Checking for them should be ignored, so that the Certificate signed for the External Domain does not get compared to the local URI. Please add this, as a config option so we can override the default strict SSL behaviour.

Edit:
I think this only affects newer 5.6+ PHP Versions

Thanks

**Comment by t3chguy** [comment]
Found a workaround, its incomplete, but functional. You should add the string used in it to the config and add the passing of it forward. Or similar.
```
    function enableCrypto($enabled, $type)
    {
        if (version_compare(phpversion(), "5.1.0", ">=")) {
            if (!is_resource($this->fp)) {
                return $this->raiseError('not connected');
            }
            stream_context_set_option( $this->fp, array( 'ssl' => array( 'peer_name' => 'mail.webdevguru.co.uk') ) ); // +++++
            return @stream_socket_enable_crypto($this->fp, $enabled, $type);
        } else {
            $msg = 'Net_Socket::enableCrypto() requires php version >= 5.1.0';
            return $this->raiseError($msg);
        }
    }
```

**Comment by fmbiete** [comment]
Hi @t3chguy 

True, PHP 5.6 verifies, by default, the certificate. I have added some flags in the config so we can workaround any problem. Of course the recommended option is to use a valid certificate, but it won't be always possible.

Let me know if it works.

**Comment by t3chguy** [comment]
@fmbiete I use a valid certificate externally, but locally its silly having a Certificate signed to "localhost"

**Comment by fmbiete** [comment]
In that case you should disable the verification in your z-push servers, because it won't match the expected name. Changing the peer_name in the context doesn't seems sane to me.
