### ISSUE TITLE
BackendIMAP ChangesSink mechanism ignores folder changes

### ISSUE THREAD

**Issue by tickerguy** [fmbiete/Z-Push-contrib#182]
With IMAP as a back end make a folder namespace change from a native IMAP client (e.g. rename a folder, move a collection of folders into a directory, etc.)

Now go back to the phone after some period of time and select the folder view; you will see that the mobile's Exchange interface doesn't know that the folder change took place as the old names will still be present, but of course if you try to select them nothing comes up as they're not there anymore.

**Comment by fmbiete** [comment]
Indeed, you won't get folder changes until next foldersync. We will need to check them in the changesink.

**Comment by fmbiete** [comment]
Hi @tickerguy 

The referenced commit should do the trick. Test it if you can and let me know if you find any problems.

**Comment by tickerguy** [comment]
I will not be able to look at this for a couple of days but will as soon as I can reasonably get to it and report back here.  Thanks!

**Comment by tickerguy** [comment]
It appears that there are several improvements in this regard and that particular problem is solved.

I've got a new potential issue here, however... will post a new comment.
