### ISSUE TITLE
Class ImportChangesDiff contains 1 abstract method and must therefore be declared abstract

### ISSUE THREAD

**Issue by nightexcessive** [fmbiete/Z-Push-contrib#186]
I'm encountering the following error:
`PHP Fatal error:  Class ImportChangesDiff contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (IImportChanges::ImportMessageStarFlag) in /usr/share/webapps/z-push/lib/default/diffbackend/importchangesdiff.php on line 281`

I'm attempting to sync an Android phone using the combined backend (configured with IMAP, CalDAV, and CardDAV). This appears to occur any time that I attempt to move an email on that phone. It also occurs with any other Android devices that attempt to change anything.
ail on that phone. It also occurs with any other Android devices that attempt to change anything.

My installation is on commit 0670458

**Comment by corradofiore** [comment]
Me too.  PHP 5.5.24, latest version of Z-push-contrib (downloaded a few minutes ago).

I can confirm it's related to moving of messages.  I'm seeing lines like these in the Z-push log:

`13/05/2015 11:06:52 [12624] [ERROR] [myuser@mydomain.tld] LoopDetection->ProcessLoopDetectionPreviousConnectionFailed(): Command 'MoveItems' at 13/05/2015 11:06:39 with pid '12651' terminated unexpectedly or is still running.`

**Comment by nightexcessive** [comment]
As this only happens to me when using the combined backend, switching to BackendIMAP has been a hotfix to keep mail syncing. Unfortunately, that isn't a permanent fix.

**Comment by fmbiete** [comment]
Hi @nightexcessive , @corradofiore ,

Sorry about that. the referenced commit should remove the remaining bits about the Star support without breaking that functionality.

**Comment by fmbiete** [comment]
Closed as fixed.
