### ISSUE TITLE
Net/SMTP : SSL even without ssl://

### ISSUE THREAD

**Issue by MykeulGit** [fmbiete/Z-Push-contrib#189]
Hello,

I have a SMTP server which does not allow SSL/TLS.
In the config.php in imap backend, I set :
```
$imap_smtp_params = array(
        'host' => 'localhost',
        'port' => 25,
        'auth' => true,
        'username' => 'imap_username',
        'password' => 'imap_password',
);
```

But even without "ssl://" before localhost, z-push-contrib connects with TLS on localhost.

I had to change this:
```
include/Net/SMTP.php :
    public function auth($uid, $pwd, $method = '', $tls = true, $authz = '')
```

to this 
```
include/Net/SMTP.php :
    public function auth($uid, $pwd, $method = '', $tls = false, $authz = '')
```

I think it is a bug. I have no SSL enabled SMTP to test.

Regards

**Comment by fmbiete** [comment]
Hi @MykeulGit ,

I don't think that's the case. I believe that your SMTP server (localhost) is announcing STARTTLS as supported, and the SMTP class is trying to use it.

Can you check it?
```
telnet localhost 25
EHLO localhost
```
It should show a line with STARTTLS.

If that's the case you should disable it or configure it properly.
If not, let me know and we will look into it.

**Comment by MykeulGit** [comment]
Hello

You are right, my server advertise as STARTTLS.
I will try to configure it, sorry for disturbance

Regards

**Comment by fmbiete** [comment]
No problem, happened to me too :laughing:
