### ISSUE TITLE
Missing '&&'

### ISSUE THREAD

**Issue by norm2k** [fmbiete/Z-Push-contrib#192]
Hi there,
I think you are missing an && in line 177 of the file "lib/default/diffbackend/diffstate.php" just before the following: $this->syncstate[$iold]["mod"] != $new[$inew]["mod"]) {...
I think the entire line 177 should be:

if(isset($this->syncstate[$iold]["mod"]) && isset($new[$inew]["mod"]) && $this->syncstate[$iold]["mod"] != $new[$inew]["mod"]) {

**Comment by fmbiete** [comment]
Yes, that's a bug. Thanks!!
