### ISSUE TITLE
Found XXX changes

### ISSUE THREAD

**Issue by m-emelchenkov** [fmbiete/Z-Push-contrib#195]
Every time I open Inbox folder there is "01/06/2015 00:40:03 [ 7044] [INFO] [xxx@xxx.xxx] ExportChangesDiff->InitializeExporter(): Found 980 changes" in logs.

It re-syncs whole mailbox every time...

**Comment by fmbiete** [comment]
You should look for errors in your log, put it in WBXML level to follow it.

**Comment by mikhail-guru** [comment]
You are right, it's the best way for me. Unfortunately, don't have free time right now but I hope to return to this issue next time I will work on the mail server where this problem exists. Also, it could be related to Issue #194. Thanks!

**Comment by m-emelchenkov** [comment]
Let's close it. I use the latest version now, can't reproduce it.
