### ISSUE TITLE
GetBodyPreferenceBestMatch() is back in 1995

### ISSUE THREAD

**Issue by tickerguy** [fmbiete/Z-Push-contrib#198]
This is just flat wrong in 2015.  If there are multiple formats available you most-certainly do not wish to use HTML over MIME.

The reason is this -- it is not at all infrequent for a message to be delivered with multiple parts and minimal or near-nothing in the HTML or PLAIN section.  Preferring HTML over MIME results in some messages delivered to the handheld being either severely-crippled or even worse, BLANK in their body section while there is content visible via IMAP.

Therefore, I changed the default preference, preferring RTF if we have it, then MIME and then finally HTML and PLAIN.  Yes, I know, this will in some cases increase bandwidth but having an unreadable message is far worse.

```
    /**
     * Returns the best match of preferred body preference types.
     *
     * @param array             $bpTypes
     * 
     * @access public
     * @return int
     */
//
// KD - Change to MIME if both HTML and MIME are available; the reason is
// that you have to be nuts to not want the attachments and full message!
// This isn't 1995 and dial-up modems, folks.
//
    public static function GetBodyPreferenceBestMatch($bpTypes) {
        // The best choice is RTF, then HTML and then MIME in order to save bandwidth
        // because MIME is a complete message including the headers and attachments
        if (in_array(SYNC_BODYPREFERENCE_RTF, $bpTypes))  return SYNC_BODYPREFERENCE_RTF;
        if (in_array(SYNC_BODYPREFERENCE_MIME, $bpTypes)) return SYNC_BODYPREFERENCE_MIME;
        if (in_array(SYNC_BODYPREFERENCE_HTML, $bpTypes)) return SYNC_BODYPREFERENCE_HTML;
        return SYNC_BODYPREFERENCE_PLAIN;
    }
```

**Comment by tickerguy** [comment]
This is not fully effective; it is functional if you resync but not on initial if you have the device set to get other than the full message (e.g. headers only) -- I am still working this issue.

**Comment by fmbiete** [comment]
I'm not sure about this change, by default.
Some carriers charges extra after the accorded bandwidth is used, even on corporate accounts. MIME will be a bad choice in those cases, so maybe this should be a global option and let the admin choose.

**Comment by tickerguy** [comment]
I refactored the entire "choose which format" code in imap.php a few days ago; it is running well now, and that included a config.php option for it.  I'll send up a diff either later today or tomorrow.

**Comment by tickerguy** [comment]
Here is my refactor on the body component selection code:
```
            //Select body type preference
            $bpReturnType = SYNC_BODYPREFERENCE_PLAIN;
            if ($bodypreference !== false) {
                $bpReturnType = Utils::GetBodyPreferenceBestMatch($bodypreference); // changed by mku ZP-330
            }
            ZLog::Write(LOGLEVEL_DEBUG, sprintf("BackendIMAP->GetMessage - getBodyPreferenceBestMatch: %d", $bpReturnType));

// KD 2015-06-11 If we have a multipart message and the config file wants it set
// default to MIME; this is 2015 and you ought to get the pretty if possible.
//
            if (
                (defined('DEFAULT_MIME_ON') && is_multipart($message)) ||
                        is_smime($message)
            ) {
                $bpReturnType = SYNC_BODYPREFERENCE_MIME;
            } else {

            //Get body data
                Mail_mimeDecode::getBodyRecursive($message, "plain", $plainBody);
                Mail_mimeDecode::getBodyRecursive($message, "html", $htmlBody);
                $htmlBody = str_replace("\n","\r\n", str_replace("\r","",$htmlBody));
                $plainBody = str_replace("\n","\r\n", str_replace("\r","",$plainBody));
// KD 2015-06-11 If we have HTML in the main body, use it.
//
                if ($htmlBody !== "")
                    $bpReturnType = SYNC_BODYPREFERENCE_HTML;
            }

            if (Request::GetProtocolVersion() >= 12.0) {
                $output->asbody = new SyncBaseBody();

```

And in mime_encode.php:
```
/*
 * Detect if the message is multipart; if so then make it a MIME message
 */
function is_multipart($message) {          
    $res = false;
    if (
        (isset($message->ctype_primary) && $message->ctype_primary == "multipart") && (isset($message->ctype_secondary) && ($message->ctype_secondary == "alternative") || ($message->ctype_secondary == "related"))) {
                
        $res = true;
    }
    return $res;
}
```

The heuristic is:

1. If "DEFAULT_MIME_ON" is defined in the config.php file AND the message is a multipart one OR we have an S_MIME message (of any sort) then we transmit it in MIME format.

2. If those two tests fail then we have either HTML or PLAIN.  If there's a HTML body prefer it always; a *converted* HTML message (by tag stripping) is always going to be ugly and may be flatly-unreadable.  Remove that conversion entirely (it's functionally worthless.)

There are a material number of email clients that will emit an HTML-only message body unless told to send in plain text and when they do that converting to plain text is a *huge* lose for the user.  In fact, many of those messages border on completely unreadable if you simply tag-strip them, which is what the previous code did.

I've been running the code this way now all weekend and it has yet to mishandle anything.  The DEFAULT_MIME_ON switch (which I have turned on) allows those who do not want to override the GetBodyPreferenceBestMatch() setting when a MIME message is found to be accommodated but there are other formats embedded to do so -- but at the cost of potentially losing embedded images and similar, as if you don't send it in MIME format originally then the attached components in some cases disappear entirely (particularly if there is no HTML reference to them in the HTML body.)

**Comment by tickerguy** [comment]
Testing now... :)

**Comment by tickerguy** [comment]
Looks good....
