### ISSUE TITLE
is_smime undefined

### ISSUE THREAD

**Issue by norm2k** [fmbiete/Z-Push-contrib#204]
ERROR:
/usr/share/z-push-master/backend/imap/mime_encode.php:309 Use of undefined constant is_smime - assumed 'is_smime'

I Think line 309 should be:
    if (is_smime($message) && !($message->ctype_primary == "multipart" && $message->ctype_secondary == "signed")) {

**Comment by fmbiete** [comment]
Of course!! Fixed.
