### ISSUE TITLE
possible imap.php add_address_to_list problem

### ISSUE THREAD

**Issue by norm2k** [fmbiete/Z-Push-contrib#205]
This prevents me from receiving new email on my smart phone...
ERROR:
PHP Fatal error:  Call to undefined function add_address_to_list() in /usr/share/z-push-master/backend/imap/imap.php on line 1262

I don't think my environment like the function add_address_to_list with the $addresses variable as a reference.  I am on PHP 5.4.41-0+deb7u1

**Comment by fmbiete** [comment]
Fixed in e047f69251b5171ddc22146f85e64ee4f816933d
