### ISSUE TITLE
mime.types with Apache's open_basedir restriction 

### ISSUE THREAD

**Issue by jbacksch** [fmbiete/Z-Push-contrib#210]
When using the Apache's open_basedir restriction to limit the access of php scripts to certain directories, the mime.types for the IMAP backend should be configurable, too, and not fixed to /etc/mime.types.

**Comment by tickerguy** [comment]
Why not symlink it?

**Comment by fmbiete** [comment]
In a selinux system this also could cause an error.

Parametrized with default value to /etc/mime.types
