### ISSUE TITLE
Can not send mail with Iphone 5 ( IOS 8.4)

### ISSUE THREAD

**Issue by gborysiak** [fmbiete/Z-Push-contrib#215]
Hi,

I configured z-push with dovecot as IMAP server and postfix for SMTP.
I configured my mailbox as exchange server on my iphone without problem.
But I can fetch email but sending is not working.

In log file, I get the following error  [SMTP:  (code: 554, response: 5.5.1 Error: no valid recipients)

PS : 
I tested successfully send email using testing-imap_smtp.php script to define the configuration.

**Comment by fmbiete** [comment]
Hi @gborysiak 

Put your log in WBXML level and try to send a message. In the log you will see the message that you try to send, and most importantly the TO, CC headers.
Also you will have the original message as sent from your iPhone and compare against the final.

Are they empty? Are they equals?

**Comment by gborysiak** [comment]
Hi @fmbiete 

I configured WBXML log level for my user but I can not find any XML about headers.

20/07/2015 09:02:30 [20173] [DEBUG] [a@b.com] [applc32jgu3fdtwg] BackendIMAP->SendMail(): RFC822: 1 bytes  forward-id: 'false' reply-id: 'false'
parent-id: 'false' SaveInSent: 'true' ReplaceMIME: 'false'
20/07/2015 09:02:30 [20173] [WBXML] [a@b.com] [applc32jgu3fdtwg] RFC822: ^@
20/07/2015 09:02:30 [20173] [DEBUG] [a@b.com] [applc32jgu3fdtwg] BackendIMAP->SendMail(): We get the new message
20/07/2015 09:02:30 [20173] [ WARN] [a@b.com] [applc32jgu3fdtwg] /var/www/z-push-contrib/include/mimeDecode.php:512 Uninitialized string offset:
0 (8)
20/07/2015 09:02:30 [20173] [DEBUG] [a@b.com] [applc32jgu3fdtwg] BackendIMAP->SendMail(): We get the From and To
20/07/2015 09:02:30 [20173] [DEBUG] [a@b.com] [applc32jgu3fdtwg] BackendIMAP->getFromHeaderValue(): No From address defined, we try for a default
 one

Any idea ?

**Comment by fmbiete** [comment]
The full message that your phone is passing to the server is "^@".
That message must be truncated at the nginx/apache level or your client is sending a broken message.

You don't have from, or to, or subject, or... well, you don't have message, so everything will fail.

Take another look at your configs (in the wiki pages and the docker folder have examples).

**Comment by gborysiak** [comment]
Hi,

I checked the configuration and find no error. I use another exchange account with an office365 server without problem.

Which parameter in apache/php could truncate message ?

**Comment by gborysiak** [comment]
ok I solve the problem. I made a mistake when configuring apache alias.
i forget to add index.php ....
