### ISSUE TITLE
Documentation - Update path

### ISSUE THREAD

**Issue by benbeton** [fmbiete/Z-Push-contrib#217]
Hi,

I'm using this a few months now and it is working great. A few times in the past days I thought about keeping the installation up to date. So I search in the Doc, but there is now documentation how to update the installation.

can anyone describe the necessary steps? Thx!

**Comment by fmbiete** [comment]
Keeping the installation up to date is pretty easy, although a bit time consuming.

1. Get the last code in a temporal folder
2. Diff config.php files (there is one config in the root folder and in the folder of each backend you use). Apply your changes
3. Make a backup of your z-push folder
4. Move your temporal folder to the z-push folder

**Comment by mporcheron** [comment]
For reference: I've been doing this using git rebasing (with a branch for personal configuration changes) as this makes it a lot less manual.

**Comment by benbeton** [comment]
sounds interesting, how to achieve, that all files except the config are update on the personal branch?

**Comment by mporcheron** [comment]
##### Setup
1. [Clone the repository to your web server](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository)
2. `git checkout -b config` to create the new _config_ branch with the local configuration 

##### Updating
1. Backup the local repository (or even better: also do this on a non-live copy)
2. `git checkout master`
3. `git pull origin master` to update the local master branch
4. `git checkout config`
3. `git rebase master` to rebase the offline _config_ branch
4. Solve the conflicts (which will occur if the configuration files have been changed in the master)

**Comment by fmbiete** [comment]
@mporcheron Kudos!! :100: 

Do you mind if I put those in a INSTALL_UPDATE_FROM_GIT file?

**Comment by mporcheron** [comment]
Of course not 👍🏻
