### ISSUE TITLE
Undefined variable: htmlBody (8)

### ISSUE THREAD

**Issue by milch** [fmbiete/Z-Push-contrib#218]
Hi,

I configured `BackendIMAP` to use SMTP to send mails. Unfortunately, I get the following errors in the log when sending an email:

```
05/08/2015 22:53:59 [    8] [WARN]  /var/www/z-push/backend/imap/imap.php:432 Undefined variable: htmlBody (8)
05/08/2015 22:53:59 [    8] [ERROR] BackendIMAP->saveSentMessage(): The email could not be saved to Sent Items folder. Check your configuration.
```

The Sent folder is set to the same value as in my `dovecot` configuration. Any ideas?

**Comment by milch** [comment]
I should add that the mails arrive at the recipient, but the content is empty.

**Comment by fmbiete** [comment]
Sorry, I left the wrong variable name after refactoring that function.

The referenced commit should fix it.
