### ISSUE TITLE
WBXMLDecoder::readRemainingData() is missing

### ISSUE THREAD

**Issue by mta59066** [fmbiete/Z-Push-contrib#222]
lib/request/requestprocessor.php uses readRemainingData() method under WBXMLDecoder, but that doesn't seem to exist there.

It looks like this method is available in the upstream Z-Push distribution though.

http://svn.zpush.net/diff.php?repname=Z-Push&path=%2Ftrunk%2Fsrc%2Flib%2Fwbxml%2Fwbxmldecoder.php&rev=1948

Thanks

--
Mehmet

**Comment by fmbiete** [comment]
Indeed, the method is missing. Merged back from upstream.

Thanks!!
