### ISSUE TITLE
Version 2.2 of Z-push released

### ISSUE THREAD

**Issue by polytan02** [fmbiete/Z-Push-contrib#223]
I notice in the svn of z-push http://svn.zpush.net/listing.php?repname=Z-Push&path=%2Frelease%2F2.2%2F&#ae325ee280b06e203e18909973f897263 that version 2.2 is released (version 1981).

This depot is at an lower reference, does it means we are missing a few features / bug correction ?

**Comment by fmbiete** [comment]
Yes, it means that.

I have updated the repo, but svn.zpush.net is obsolete. As of today it doesn't contains the last upstream version; we will soon have a new URL to share.
