### ISSUE TITLE
Regression - Can't map users

### ISSUE THREAD

**Issue by redhell** [fmbiete/Z-Push-contrib#225]
Hi,

im using the latest master from git.
I want to map a user@mail.com to user. Referring to the documentation

z-push-admin.php -a map -u user@mail.com -b BackendCardDAV -t user

should make it but i get following error:

ERROR: Wrong 'type'. Possible values are: 'email', 'calendar', 'contact', 'task', 'note' or a 44 byte long folder id (as hex).

**Comment by fmbiete** [comment]
Hi @redhell 

The referenced commit should do the trick. Could you confirm it?

Thanks!!

**Comment by redhell** [comment]
fixed in latest git
