### ISSUE TITLE
Windows 10 Calendar/Email does not interoperate

### ISSUE THREAD

**Issue by tickerguy** [fmbiete/Z-Push-contrib#226]
Windows 10 includes an EAS client for Email, contacts and calendars.

However, while it appears to add correctly to Z-push, nothing actually syncs.  There is no error shown, however, in the logs and a status CLAIMS everything is ok...

-----------------------------------------------------
DeviceId:               ***************************
Device type:            WindowsMail
UserAgent:              MSFT-WP/10.0.10240
Device Model:           Windows Device
Device friendly name:   KARL-DESKTOP
Device OS:              Windows Phone 10.0.10240
Device OS Language:     English
Device Operator:        OperatorName
ActiveSync version:     14
First sync:             2015-08-18 07:55
Last sync:              2015-08-18 07:56
Total folders:          8
Synchronized folders:   4
Synchronized data:      Emails Tasks Calendars Contacts
Status:                 OK
WipeRequest on:         not set
WipeRequest by:         not set
Wiped on:               not set
Attention needed:       No errors known

The only thing I see is that the ActiveSync version is reported as "14" rather than "14.0" as is the case for my BlackBerry....... Hmmm.....

Just opening this here, will see what I can figure out when I can find some spare cycles to work on it.

**Comment by tickerguy** [comment]
On first blush I do not see an obvious problem in the XML logs against a test user..... unfortunately.

**Comment by polytan02** [comment]
Just to be clear, what do you mean by "does not operate" ? 

I'm just asking as on my side I can sencd emails from the win10 mail client connected via z-push. I can also send calendar invit.

At this stage the issues I have with it are :  
* Charset issue : emails are all "disgusting" a soon as you use letters out of basic ascii
* I cannot see calendar invitations coming through, even if they are in the inbox. It's like the mail client "filters" the display.

**Comment by tickerguy** [comment]
I added the account and it does not sync at all; nothing comes up, even though there are emails in the inbox.  I also cannot add any calendar events (the button doesn't work)

**Comment by tickerguy** [comment]
This looks very much like a client problem and there are some other reports of trouble around the 'net.  I have looked at the WBXML for a newly-configured account with one message in the INBOX and the provisioning goes, and then the message is in fact retrieved -- but it never appears in the client.

Going to close this for now as it doesn't appear to be a Z-Push problem, but rather something Microsoft either broke with an update or simply doesn't work correctly at this time.
