### ISSUE TITLE
AWL libs are not located automatically

### ISSUE THREAD

**Issue by tmuncks** [fmbiete/Z-Push-contrib#238]
On a brand new install (first time with z-push-contrib), IMAP only Backend enabled, iCalendar keeps complaining about a missing XMLElement.php, even though libawl-php has already been installed.

It took a while for me to identify the issue and in the end, adding the following to top of z-push config.php worked around the problem:

$awlpath = '/usr/share/awl/inc';
set_include_path(get_include_path() . PATH_SEPARATOR . $awlpath);

Perhaps some autodetection would be a better wat to solve this in the code? Or add a config option for it?

**Comment by fmbiete** [comment]
You need to modify include_path variable in your /etc/php.ini, to add your awl folder.
Maybe I should add a explicit note in the INSTALL file.
