### ISSUE TITLE
z-push 2.2.6 is out

### ISSUE THREAD

**Issue by polytan02** [fmbiete/Z-Push-contrib#240]
Hi,

I noticed that z-push 2.2.6 is out :  https://z-push.org/z-push-2-2-6-final-released/

Looking at their git rep, I couldn't see any carddav or caldav stuff. Have they dropped these great backends ? 
https://stash.z-hub.io/projects/ZP/repos/z-push/browse?at=refs%2Fheads%2Frelease%2F2.2.6

**Comment by fmbiete** [comment]
This is completely my fault; I have been really busy with other stuff and I have neglected this one. The push and merge request are yet to be done.

Let's see if I can do it before the end of the year :pray:

**Comment by polytan02** [comment]
But regarding the other comment, have they dropped carddav and caldav support from the official tree ?

**Comment by fmbiete** [comment]
Carddav and caldav support has not been ever in upstream. I'm going to contribute them, but the first step was to merge some requirements (done in 2.2.4).
https://jira.z-hub.io/browse/ZP-684
https://jira.z-hub.io/browse/ZP-685

**Comment by polytan02** [comment]
I didn't know this part of the story and I'm even more impressed by your work then ! 
Well done.

**Comment by raoulbhatia** [comment]
Few days back I've installed z-push 2.3.9 via http://z-push.org/z-push-2-3-9-final-release/ .
First tests look good :-) awesome stuff!
