### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by bax-** [fmbiete/Z-Push-contrib#243]
Hello!

Any information about the compatibility of Z-Push and PHP7?

**Comment by fmbiete** [comment]
It's planned in upstream for 2.3.0
https://jira.z-hub.io/browse/ZP-804

**Comment by bax-** [comment]
Thanks for the update!

**Comment by polytan02** [comment]
@fmbiete by the way, are we currently using the latest official ZP sources ?

**Comment by fmbiete** [comment]
No, we are using an old version (august 2015). 2.2.6 has some code from this repo and changes not available here; I'm working into merging them and contribute more to upstream.

**Comment by bax-** [comment]
Hi! Any news on the merging? Upstream works with PHP7 now but it lacks redistribution support so I guess it isn't able to run it in FreeBSD jails…

**Comment by compuguy** [comment]
@bax- No clue. Upstream works with PHP 7.2 as well.
