### ISSUE TITLE
Broken attachments

### ISSUE THREAD

**Issue by bax-** [fmbiete/Z-Push-contrib#252]
The attachments I'm sending from my iPhone get broken during transfer.
Images become corrupted.
This is even the case for really small (35kB) images.
It makes no difference if I enable S/MIME on the device or not. DKIM signatures are being broken as well because of that.
The mail in the "Sent" folder displays correctly.
I don't find anything in my Z-Push, PHP-FPM or NGINX logs that indicates an error.

**Comment by bax-** [comment]
It seems like that was a problem within PHP mail().
I switched to SMTP and now everything works as expected.
Don't know what exactly caused this.

**Comment by bax-** [comment]
ssmtp (sendmail replacement) also works. I guess sendmail does as well.
Seems to be a problem with mail() and attachments.

**Comment by fmbiete** [comment]
I should have deprecayed mail() a long time ago. Maybe is related to some b64 bug in PHP, but I don't believe is worth the time to investigate it.
