### ISSUE TITLE
Cron jobs?

### ISSUE THREAD

**Issue by bax-** [fmbiete/Z-Push-contrib#253]
Are there any Cron jobs recommended regularly to keep everything fluffy?
Like a resync once a year or clear loop or fixstates monthly?

**Comment by fmbiete** [comment]
No, I don't cron anything. Z-Push should heal by itself, and you would be hiding a bug.
But, I "remove" deleted devices from a gui when an admin disable his permission to sync.

You could manually "remove" deleted devices, but it's not a big deal, unless you have thousand of devices not being used.
