### ISSUE TITLE
Wrong Time with BackendCalDAV

### ISSUE THREAD

**Issue by Offerel** [fmbiete/Z-Push-contrib#286]
At this time, i try to connect Z-Push with BackendIMAP to Nextcloud. On my Android Device, i use DavDroid to sync CalDAV. All Events have the correct start time as in the WebGUI. If i sync the same Calendar with Z-Push some (not all) events are shifted + 1 hour. 

Global PHP Timezone is Europe/Berlin and in Z-Push Settings i have the directive define('TIMEZONE', 'Europe/Berlin').

Why are some events shifted and others not? What can i do?

**Comment by Offerel** [comment]
I think, i have found something in the Logfile:

TimezoneUtil::getMSTZnameFromTZName() no MS name found for 'W. Europe Standard Time'. Returning '(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'

Can i fix this, when i change the timezone info for this events? What should i use as format? "Europe/Berlin" or some other?

**Comment by holdenger** [comment]
@Offerel I have the same exact problem. How did you resolve this?

**Comment by Offerel** [comment]
I cant remember, since i use now SabreDAV. NextCloud itself is to slow for my needs. In SabreDAV there was a Fix for this issue. I have seen also a Fix in a Z-Push Beta Trunk. I didn't know, if this was released yet.

**Comment by holdenger** [comment]
Well, i use SabreDAV too (not own/nextcloud), i use latest Z-Push (2.3.5) and i have this problem. Probably i should try latest SabreDAV version.
