### ISSUE TITLE
feature request: handling spam

### ISSUE THREAD

**Issue by bax-** [fmbiete/Z-Push-contrib#53]
I don't know how much of this is being handled by z-push:
I mark an email as spam on my iPhone - it then get's moved to my "junk" folder.
What I would like in this process to be done is add / set an IMAP-flag "//seen" and "$junk".

**Comment by fmbiete** [comment]
As 654a12bb27be194f8b378a2a9926e9d6f8d0bd3d we support the Junk folder for iOS devices. So this should be done.

Thanks!!
