### ISSUE TITLE
Fatal: Class 'iCalComponent' not found in imap.php

### ISSUE THREAD

**Issue by erenoglu** [fmbiete/Z-Push-contrib#71]
Hi,
After the other issue was solved, I got stuck again when downloading messages. The primary error on the webserver log was:

2014-07-13 13:42:28: (mod_fastcgi.c.2673) FastCGI-stderr: PHP Fatal error:  Class 'iCalComponent' not found in /usr/share/z-push/backend/imap/imap.php on line 2403

Other than that, in z-push logs, I've seen the following, probably related to the above, when the php session dies due to above error and mobile still tries to sync:

13/07/2014 14:05:08 [20193] [DEBUG] [emre] LoopDetection->Detect(): case 3.3 detected - in loop mode, increase loop counter
13/07/2014 14:05:08 [20193] [DEBUG] [emre] LoopDetection->Detect(): case 3.3.1 detected - broken item should be next, attempt to ignore it - id '15108'
13/07/2014 14:05:08 [20193] [DEBUG] [emre] LoopDetection->Detect(): loop data: loopcount(9), maxCount(536), queued(524), ignored(false)
13/07/2014 14:05:08 [20193] [ WARN] [emre] Mobile loop detected! Messages sent to the mobile will be restricted to 2 items in order to identify the conflict

PS. The issue on github master checked out today. note that this z-push uses IMAP backend, without a calendar provider, but there are emails with calendar invitations inside (outlook/exchange style)

**Comment by benbeton** [comment]
on my web server I can't install the required pakage and only need "Backend Imap" no ICalendar ...
can I comment out some code the get rid of the problem? 

thanks

**Comment by fmbiete** [comment]
@benbeton you will lose functionality and face errors.

If you cannot install the awl libs in your server, you can put it inside your z-push folder. For example:

1.- Copy the awl library inside z-push/awl
2.- Modify z-push/composer.json changing this line:
```
        "classmap": ["autodiscover/", "include/", "lib/", "awl/inc"],
```
3.- Download and run composer to update your autoload files:
```
curl -sS https://getcomposer.org/installer | php
php composer.phar dump-autoload -o
```

**Comment by benbeton** [comment]
@fmbiete at first, your version is working great thank you!!! what I did: 
commented out the following in "include/iCalendar.php"

*require_once('XMLElement.php');
* Commented out, only needed by deprecated functions
*require_once('AwlQuery.php');
*/

that is working, but will definitely do your suggestion, thank you for your reply!

regards!

**Comment by m-emelchenkov** [comment]
@fmbiete It will not work. "include/iCalendar.php" does not includes autodiscover so it's necessary to implicitly set path in iCalendar.php to "require_once('/usr/share/awl/inc/XMLElement.php');" (in case of Ubuntu which installs 'awl' to /usr/share/awl)

**Comment by fmbiete** [comment]
@m-emelchenkov That workaround was only meant to be used when you don't have full access to your server.
If you have access you should modify your include_path as I said before.

**Comment by m-emelchenkov** [comment]
@fmbiete I didn't notice it, thanks. It should be added to installation instructions.
