### ISSUE TITLE
Whenever I try to create/change a calendar appointment it doesnt update on server

### ISSUE THREAD

**Issue by jkaberg** [fmbiete/Z-Push-contrib#91]
See log,

> 10/09/2014 20:56:59 [30522] [INFO] [joel@jkaberg.com] Version='SVN-trunk-r1907' method='POST' from='46.249.234.21' cmd='Sync' getUser='joel@jkaberg.com' devId='androidc1314625929' devType='Android'
> 10/09/2014 20:57:01 [30522] [INFO] [joel@jkaberg.com] StatusException: ImportChangesDiff->ImportMessageChange('20140910T131305Z-3520eeb88d73d81e6abe871df201618f.ics','SyncAppointment'): Conflict detected. Data from PIM will be dropped! Server overwrites PIM. User is informed. - code: 7
> 10/09/2014 20:57:01 [30522] [INFO] [joel@jkaberg.com] Processed '1' incoming changes
> 10/09/2014 20:57:01 [30522] [INFO] [joel@jkaberg.com] ExportChangesDiff->InitializeExporter(): Found '1' changes
> 10/09/2014 20:57:02 [30266] [INFO] [joel@jkaberg.com] Version='SVN-trunk-r1907' method='POST' from='46.249.234.21' cmd='Sync' getUser='joel@jkaberg.com' devId='androidc1314625929' devType='Android'
> 10/09/2014 20:57:04 [30266] [INFO] [joel@jkaberg.com] StatusException: ImportChangesDiff->ImportMessageChange('owncloud-9e1e4ae99b1f8a592023c0d0af063317.ics','SyncAppointment'): Conflict detected. Data from PIM will be dropped! Server overwrites PIM. User is informed. - code: 7

Any idea? (backend is ownCloud) Config files can be viewed here, https://github.com/mail-in-a-box/mailinabox/tree/master/conf/zpush

Creating/Changeing or deleting an appointment in ownCloud works just fine, but I canno't change/create appointments in calendar app @ android (delete works)

PS: I think this was working before, perhaps broken in a recent update? (mailinabox updates z-push from your branch whenever theres a new verision number)

**Comment by chises** [comment]
Hi all,
i have the same issue!
setup: 
root@vsrv03 ~ # uname -a
Linux vsrv03.xxxx 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux

root@vsrv03 ~ # nginx -v
nginx version: nginx/1.2.1

z-push "SVN-trunk-r1931"

using owncloud 8 that provides the caldav backend.

If i change 
    define('SYNC_CONFLICT_DEFAULT', SYNC_CONFLICT_OVERWRITE_PIM);
to
    define('SYNC_CONFLICT_DEFAULT', SYNC_CONFLICT_OVERWRITE_SERVER);

it is working.

LOG START:
a18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] -------- Start
18/02/2015 16:02:13 [27218] [ INFO] [test@domain.net] Version='SVN-trunk-r1931' method='POST' from='88.217.226.9' cmd='Sync' getUser='test@domain.net' devId='7027e35ab76d498198a966ed322e1861' 

devType='WindowsOutlook'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Used timezone 'Europe/Berlin'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Including backend file: '/var/www/z-push/backend/combined/combined.php'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Including backend file: '/var/www/z-push/backend/imap/imap.php'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Including backend file: '/var/www/z-push/backend/caldav/caldav.php'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Including backend file: '/var/www/z-push/backend/carddav/carddav.php'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Combined 3 backends loaded.
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Request::ProcessHeaders() ASVersion: 14.0
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] ZPush::CommandNeedsProvisioning(0): true
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] FileStateMachine->GetState() on file: '/var/lib/z-push/1/6/7027e35ab76d498198a966ed322e1861-devicedata'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] ASDevice data loaded for user: 'test@domain.net'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] TopCollector(): Initialized mutexid Resource id #123 and memid Resource id #124.
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] LoopDetection(): Initialized mutexid Resource id #125 and memid Resource id #126.
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] ZPush::HierarchyCommand(0): false
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] DeviceManager->ProvisioningRequired('0') saved device key '-1': false
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] ZPush::CommandNeedsAuthentication(0): true
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Combined->Logon('test@domain.net', '',***))
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] BackendIMAP->Logon(): User 'test@domain.net' is authenticated on '{localhost:993/imap/ssl/novalidate-cert}'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] BackendCalDAV->Logon(): User 'test@domain.net' is authenticated on CalDAV
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] BackendCardDAV->Logon(): User 'test@domain.net' is authenticated on 'https://vsrv03.my-

chi.de:443/owncloud/remote.php/carddav/addressbooks/test@domain.net/'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] BackendCardDAV::discoverAddressbooks() Found addressbook 'https://vsrv03.my-

chi.de:443/owncloud/remote.php/carddav/addressbooks/test@domain.net/kontakte/'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Combined->Logon() success
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Combined->Setup('test@domain.net', 'true', '')
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Combined->Setup() success
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] ZPush::CommandNeedsPlainInput(0): false
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I  <Synchronize>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I   <Folders>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I    <Folder>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     <SyncKey>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I      {23c1a77b-b793-4d1e-8333-7aca95707472}10
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     </SyncKey>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     <FolderId>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I      c/Cpersonal
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     </FolderId>
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] FileStateMachine->GetState() on file: '/var/lib/z-push/1/6/7027e35ab76d498198a966ed322e1861-23c1a77b-b793-4d1e-8333-7aca95707472-fd'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] SyncParameters->UseCPO('DEFAULT')
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] SyncCollections->AddCollection(): Folder id 'c/Cpersonal' : ref. PolicyKey '-1', ref. Lifetime '3540', last sync at '1424271561'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] SyncCollections->AddCollection(): Updated reference PolicyKey '-1', reference Lifetime '3540', Last sync at '1424271561'
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     <DeletesAsMoves>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I      0
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     </DeletesAsMoves>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     <GetChanges>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I      0
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     </GetChanges>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     <WindowSize>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I      512
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     </WindowSize>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     <Options>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I      <FilterType>
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] SyncParameters->UseCPO('DEFAULT')
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I       0
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I      </FilterType>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I      <AirSyncBase:BodyPreference>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I       <AirSyncBase:Type>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        1
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I       </AirSyncBase:Type>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I       <AirSyncBase:AllOrNone>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        1
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I       </AirSyncBase:AllOrNone>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I      </AirSyncBase:BodyPreference>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     </Options>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     <Perform>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I      <Modify>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I       <ServerEntryId>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        owncloud-fe95bc1821d43152de2e8ea2ac047cad.ics
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I       </ServerEntryId>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I       <Data>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        <POOMCAL:Timezone>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I         

xP///00AaQB0AHQAZQBsAGUAdQByAG8AcADkAGkAcwBjAGgAZQAgAFoAZQBpAHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAFAAMAAAAAAAAAAAAAAE0AaQB0AHQAZQBsAGUAdQByAG8AcADkAGkAcwBjAGgAZQAgAFMAbwBtAG0AZQByAHoAZQBpAHQAAAAA

AAAAAAAAAAMAAAAFAAIAAAAAAAAAxP///w==
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        </POOMCAL:Timezone>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        <POOMCAL:DtStamp>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I         20150218T150207Z
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        </POOMCAL:DtStamp>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        <POOMCAL:StartTime>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I         20150216T230000Z
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        </POOMCAL:StartTime>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        <POOMCAL:Subject>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I         jupp
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        </POOMCAL:Subject>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        <POOMCAL:UID>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I         184520936e
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        </POOMCAL:UID>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        <POOMCAL:OrganizerName>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I         test@domain.net
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        </POOMCAL:OrganizerName>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        <POOMCAL:OrganizerEmail>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I         test@domain.net
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        </POOMCAL:OrganizerEmail>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        <POOMCAL:Location>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I         ADASDASD
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        </POOMCAL:Location>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        <POOMCAL:EndTime>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I         20150217T230000Z
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        </POOMCAL:EndTime>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        <POOMCAL:BusyStatus>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I         2
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        </POOMCAL:BusyStatus>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        <POOMCAL:AllDayEvent>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I         1
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        </POOMCAL:AllDayEvent>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        <POOMCAL:ResponseRequested>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I         1
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I        </POOMCAL:ResponseRequested>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I       </Data>
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Supported variables to be unset: categories,sensitivity,recurrence,reminder,exceptions,attendees,meetingstatus,disallownewtimeprop
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Sync->getImporter(): initialize importer
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Sync->loadStates(): loading states for folder 'c/Cpersonal'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] FileStateMachine->GetState() on file: '/var/lib/z-push/1/6/7027e35ab76d498198a966ed322e1861-23c1a77b-b793-4d1e-8333-7aca95707472-10'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] FileStateMachine->CleanStates(): Deleting file: '/var/lib/z-push/1/6/7027e35ab76d498198a966ed322e1861-23c1a77b-b793-4d1e-8333-7aca95707472-

fs-8'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] FileStateMachine->GetState() on file: '/var/lib/z-push/1/6/7027e35ab76d498198a966ed322e1861-23c1a77b-b793-4d1e-8333-7aca95707472-fs-10'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] ZPush::GetAdditionalSyncFolderStore('c/Cpersonal'): 'false'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Combined->Setup('', 'false', '')
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Combined->Setup() success
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Combined->GetImporter() Content: ImportChangesCombined:('c/Cpersonal')
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] ImportChangesCombined->Config(...)
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] ImportChangesCombined->Config() success
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] ImportChangesCombined->ConfigContentParameters()
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] ImportChangesCombined->ConfigContentParameters() success
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] LoopDetection->SetSyncStateUsage(): uuid: 23c1a77b-b793-4d1e-8333-7aca95707472  counter: 10
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] BackendCalDAV->StatMessage('Cpersonal','owncloud-fe95bc1821d43152de2e8ea2ac047cad.ics')
18/02/2015 16:02:13 [27218] [ INFO] [test@domain.net] StatusException: ImportChangesDiff->ImportMessageChange('owncloud-fe95bc1821d43152de2e8ea2ac047cad.ics','SyncAppointment'): Conflict 

detected. Data from PIM will be dropped! Server overwrites PIM. User is informed. - code: 7
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Sync->importMessage(): message imported
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I      </Modify>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I     </Perform>
18/02/2015 16:02:13 [27218] [ INFO] [test@domain.net] Processed '1' incoming changes
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] FileStateMachine->SetState() written 424 bytes on file: '/var/lib/z-push/1/6/7027e35ab76d498198a966ed322e1861-23c1a77b-b793-4d1e-8333-

7aca95707472-fs-10'
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I    </Folder>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I   </Folders>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] I  </Synchronize>
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] HandleSync(): Start Output
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] WBXMLEncoder->startWBXML() type: vnd.ms-sync.wbxml
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Folder type: Calendar
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O  <Synchronize>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O   <Folders>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O    <Folder>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O     <SyncKey>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O     {23c1a77b-b793-4d1e-8333-7aca95707472}11
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O     </SyncKey>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O     <FolderId>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O     c/Cpersonal
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O     </FolderId>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O     <Status>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O     1
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O     </Status>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O     <Replies>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O      <Modify>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O       <ServerEntryId>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O       owncloud-fe95bc1821d43152de2e8ea2ac047cad.ics
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O       </ServerEntryId>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O       <Status>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O       7
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O       </Status>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O      </Modify>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O     </Replies>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O    </Folder>
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] FileStateMachine->SetState() written 152 bytes on file: '/var/lib/z-push/1/6/7027e35ab76d498198a966ed322e1861-23c1a77b-b793-4d1e-8333-

7aca95707472-11'
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] SyncCollections->SaveCollection(): Data of folder 'c/Cpersonal' changed
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] FileStateMachine->SetState() written 842 bytes on file: '/var/lib/z-push/1/6/7027e35ab76d498198a966ed322e1861-23c1a77b-b793-4d1e-8333-

7aca95707472-fd'
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O   </Folders>
18/02/2015 16:02:13 [27218] [WBXML] [test@domain.net] O  </Synchronize>
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] WBXMLEncoder->endTag() WBXML output completed
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Combined->Logoff()
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] BackendIMAP->Logoff(): IMAP connection closed
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] BackendCalDAV->Logoff()
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] BackendCardDAV->Logoff()
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] Combined->Logoff() success
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] LoopDetection->ProcessLoopDetectionTerminate()
18/02/2015 16:02:13 [27218] [DEBUG] [test@domain.net] -------- End
