### ISSUE TITLE
Sent folder on iOS devices

### ISSUE THREAD

**Issue by alby128** [fmbiete/Z-Push-contrib#94]
From Backend/IMAP configuration file the folder in which sent messages are stored can be selected. This setting works fine from server side, the server correctly saves sent messages in the picked folder. 

However, on iOS devices, Mail.app does not show sent messages in the "Sent" area, but it correctly shows sent messages in the chosen folder on server. 

I guess z-push-contrib does not set some attributes that flag the sent folder as such in iOS devices. Do you know how to set these properties? Does the sent folder work fine for non iOS systems?

Thanks as usual,
Alberto

**Comment by fmbiete** [comment]
As 242acef8d684f440bb1669b67b39add4c981db0f we have a working config settings for gmail.

Thanks!
